Resources:
  AppSyncHandler:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'Lambda-AppSyncHandler'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaRole-Policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - 'arn:aws:logs:us-east-1:881433986874:log-group:/aws/lambda/warriorbeat-graphql-dev-lambda_handler:*'
                  - 'arn:aws:logs:us-east-1:881433986874:log-group:/aws/lambda/warriorbeat-graphql-dev-lambda_handler:*:*'
        - PolicyName: 'LambdaRole-DynamoDB-Policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:GetItem'
                Resource:
                  # Poll Table Resources
                  - ${cf:${self:custom.stack}.PollTableArn}
                  - ${cf:${self:custom.stack}.PollTableArn}/*
                  - ${cf:${self:custom.stack}.PollOptionsTableArn}
                  - ${cf:${self:custom.stack}.PollOptionsTableArn}/*
                  - ${cf:${self:custom.stack}.PollOptionsTableArn}
                  - ${cf:${self:custom.stack}.PollOptionsTableArn}/*
                  # Users Table
                  - ${cf:${self:custom.stack}.UsersTableArn}
                  - ${cf:${self:custom.stack}.UsersTableArn}/*
                  # Articles Table
                  - ${cf:${self:custom.stack}.ArticlesTableArn}
                  - ${cf:${self:custom.stack}.ArticlesTableArn}/*
                  # Authors Table
                  - ${cf:${self:custom.stack}.AuthorsTableArn}
                  - ${cf:${self:custom.stack}.AuthorsTableArn}/*
                  # Media Table
                  - ${cf:${self:custom.stack}.MediaTableArn}
                  - ${cf:${self:custom.stack}.MediaTableArn}/*

  AppSyncServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'Lambda-AppSyncServiceRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'appsync.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'Lambda-AppSyncServiceRole-Policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'lambda:invokeFunction'
                Resource:
                  - 'arn:aws:lambda:${self:provider.region}:*:function:warriorbeat-graphql-dev-lambda_handler'
                  - 'arn:aws:lambda:${self:provider.region}:*:function:warriorbeat-graphql-dev-lambda_handler:*'
