Resources:
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-media-${self:custom.stage}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
      AccessControl: PublicRead

  MediaBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
            Resource: ${cf:${self:custom.stack}.MediaBucketArn}/*
      Bucket:
        Ref: MediaBucket

Outputs:
  MediaBucketName:
    Value:
      Ref: MediaBucket
  MediaBucketArn:
    Value: { Fn::GetAtt: [MediaBucket, Arn] }
