// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2019-03-19T01:04:30.650Z

const awsmobile = {
    aws_appsync_authenticationType: 'API_KEY',
    aws_appsync_graphqlEndpoint: 'https://gaemuk5kpffsvdqqoas4xkjruq.appsync-api.us-east-1.amazonaws.com/graphql',
    aws_appsync_region: 'us-east-1',
    aws_project_region: 'us-east-1'
};

export default awsmobile;
