Resources:
  ArticlesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: author
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      TableName: Articles-${self:custom.stage}
      GlobalSecondaryIndexes:
        - IndexName: author-index
          KeySchema:
            - AttributeName: author
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}

Outputs:
  ArticlesTableArn:
    Value: { Fn::GetAtt: [ArticlesTable, Arn] }
