Resources:
  CategoriesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      TableName: Categories-${self:custom.stage}

Outputs:
  CategoriesTableArn:
    Value: { Fn::GetAtt: [CategoriesTable, Arn] }
