Resources:
  PollTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      TableName: Polls-${self:custom.stage}
  PollOptionsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: pollId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: pollId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      TableName: PollOptions-${self:custom.stage}
      GlobalSecondaryIndexes:
        - IndexName: pollId-index
          KeySchema:
            - AttributeName: pollId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
  PollVotesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: optionId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: optionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      TableName: PollVotes-${self:custom.stage}
      GlobalSecondaryIndexes:
        - IndexName: optionId-index
          KeySchema:
            - AttributeName: optionId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: optionId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}

Outputs:
  PollTableArn:
    Value: { Fn::GetAtt: [PollTable, Arn] }

  PollOptionsTableArn:
    Value: { Fn::GetAtt: [PollOptionsTable, Arn] }

  PollVotesTableArn:
    Value: { Fn::GetAtt: [PollVotesTable, Arn] }
